services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Psr\Container\ContainerInterface $webResponders: !tagged_locator {tag: 'audioteka.web.responder'}

    _instanceof:
        Audioteka\Web\Responder: {tags: ['audioteka.web.responder']}

    Audioteka\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    Audioteka\Web\Action\:
        resource: '../src/Web/Action'
        tags: ['controller.service_arguments']

    command_handlers:
        namespace: Audioteka\Application\Command\Handler\
        resource: '%kernel.project_dir%/src/Application/Command/Handler/*.php'
        tags: [{name: messenger.message_handler, bus: command.bus}]

    query_handlers:
        namespace: Audioteka\Application\Query\Handler\
        resource: '%kernel.project_dir%/src/Application/Query/Handler/*.php'
        tags: [{name: messenger.message_handler, bus: query.bus}]
